export enum TypographyType {
  HeadingMd = "heading-md",
  HeadingMdLg = "heading-md-lg",
  HeadingLg = "heading-lg",
  HeadingXl = "heading-xl",
  HeadingXxl = "heading-xxl",
  HeadingXxxl = "heading-xxxl",
  HeadingXxxxl = "heading-xxxxl",
  Subheading = "subheading",
  SubheadingMd = "subheading-md",
  SubheadingLg = "subheading-lg",
  SubheadingXl = "subheading-xl",
  Body = "body",
  BodySm = "body-sm",
  Caption = "caption",
  Small = "small",
  Medium = "medium",
  XSmall = "x-small",
}
